server:
  port: 8088
spring:
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exshop
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.exshop_main.entity
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql



